### ISSUE TITLE
references between containers now being displayed on system diagrams

### ISSUE THREAD

**Issue by pshomov** [structurizr/java#100]
Hello,

Not sure if this is as intended but I have for example an User that uses a container and I would expect that relationship would show up when displaying system diagram for the system that owns the container and same user. Currently I have to resort to adding that connection at both levels to achieve what I want.

**Comment by simonbrowndotje** [comment]
That's the intended behaviour, because you might not want the exact same relationship shown on different levels of diagram. There is an ```addImplicitRelationships``` method though (https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/Model.java#L430) that will duplicate the user-container to user-system.

**Comment by pshomov** [comment]
Thank you @simonbrowndotje for the clarification. We met a few years back in Iceland but only now do I get a chance to put C4 model to good use. So far love structurizr, thank you!
