### ISSUE TITLE
Change setComponents method to public

### ISSUE THREAD

**Issue by zhaoruda** [structurizr/java#140]
https://github.com/structurizr/java/blob/31a78115fedb058250782f9b40aaac88bb1c584a/structurizr-core/src/com/structurizr/model/Container.java#L132

Can we change this method to public, so that we can update components.

**Comment by simonbrowndotje** [comment]
The Java client library is designed to be append-only; so you start off with an empty workspace and gradually add elements, relationships, views, etc to it. Clearing the components of an existing workspace is somewhat problematic in that it potentially invalidates some of the internal structures, and therefore the model. It can certainly be done, but, as I said, the Java client library is designed to be append-only, rather than mutable. Perhaps there's another way to achieve your goal ... what's your use case?

**Comment by zhaoruda** [comment]
My use case like this:
1、System context and Container are maintained by some one like TL in separate repo
2、Component is maintained by developers in logic repo

AS they are in different repo, and can not generated together. So I want setting components to empty when generate components again.

**Comment by simonbrowndotje** [comment]
What most people tend to do is to store a copy of the base workspace (context and containers only) as a JSON file, and then load that from disk when it's time to add components. That would be the easiest way to do this in the short-term.
