### ISSUE TITLE
Adding components to a component view of a container they are not a member of

### ISSUE THREAD

**Issue by nikolasavic-tw** [structurizr/java#142]
I'm parsing a .json file exported by Structurizr.com with a component view that contains components that don't belong to the component view's parent container.  I know with system/container views, you can just add unrelated containers to provide more context, but this feature seems to be explicitly disabled with components: https://github.com/structurizr/java/blob/c4cc3df8c462802fd3731fca7f619290aece8449/structurizr-core/src/com/structurizr/view/ComponentView.java#L139-L147

How is it possible for such a view to be exported if it should be invalid in the first place?

**Comment by simonbrowndotje** [comment]
There a number of reasons for this, including:

- The workspace wasn't created by the Java client library.
- The workspace was created by a fork of the Java client library.
- The workspace was created by an older version of the client library (before March 2016).
- The workspace was manually modified.
- etc

Having said all of this, a few people would like the ability to add "foreign" components to a component view, so that code might be removed at some point in the near future.
