### ISSUE TITLE
DeploymentNodes implied relationships

### ISSUE THREAD

**Issue by qequ** [structurizr/java#193]
I'm working on a plugin and working with relationships between deploymentNodes and containerInstances, but I'm missing several implied relationships. How does Structurizr handle these implied relationships?
Also, ContainerInstances have a `uses` method like Person, but I'm not being able to relate them with other ContainerInstances/DeploymentNodes

CC: @dgutson

**Comment by simonbrowndotje** [comment]
An overview of the implied relationships functionality can be found at https://github.com/structurizr/java/blob/master/docs/implied-relationships.md

> Also, ContainerInstances have a uses method like Person, but I'm not being able to relate them with other ContainerInstances/DeploymentNodes

This is by design ... container instance to container instance relationships should be defined as container to container relationships, and the resulting container instance to container instance relationship(s) will be automatically created when the container instances are created (i.e. when the container is added to a deployment node). The basic call stack is:

- [structurizr-dsl:ContainerInstanceParser.parse](https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/ContainerInstanceParser.java#L49)
- [structurizr-java:DeploymentNode.add(Container)](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/DeploymentNode.java#L74)
- [structurizr.java:Model.addContainerInstance](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/Model.java#L903)
- [structurizr.java:Model.replicateElementRelationships](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/Model.java#L921)

It's the `replicateElementRelationships` method that creates the container instance to container instance relationships.
