### ISSUE TITLE
Using structurizr for c code?

### ISSUE THREAD

**Issue by user-don** [structurizr/java#20]
Hi,

Apologies if this is an uninformed question. I understand that you need to use java to construct a code model that structurizr can consume. However, is it possible to analyze code that is written in a different language, such as C or C++?

**Comment by simonbrowndotje** [comment]
The "Structurizr for Java" library allows you to create a software architecture using Java code, and it also understands how to analyse Java code. It then sends a JSON document (describing the software architecture model) to structurizr.com in order to create the diagrams. There is nothing built in to analyse C or C++ code, but you could add the facility if you wanted to (e.g. by performing static analysis on the source code). A potentially better alternative might be to create a C/C++ implementation that creates the same JSON document though, which can then in turn be sent up to Structurizr. Does that help?

**Comment by thefooly** [comment]
We are interested to do the same thing from JavaScript instead of C/C++
Is there any documentation on the JSON document with the architecture model you mention?

**Comment by simonbrowndotje** [comment]
There's a (mostly) complete Swagger definition here. It needs some minor fixes, but it should be enough to get you started -> https://github.com/structurizr/java/blob/master/swagger.txt

**Comment by Zaijo** [comment]
@simonbrowndotje the link to swagger.txt is broken

**Comment by mcbeelen** [comment]
I'm not sure, but I would expect that the swagger definition of the on-premise API would be the same.
That can be you at: 
[https://github.com/structurizr/api/blob/master/swagger.txt](https://github.com/structurizr/api/blob/master/swagger.txt)

**Comment by simonbrowndotje** [comment]
Just to close this issue, an OpenAPI v3.0 specification can be found here -> https://structurizr.com/help/web-api (this applies to both the cloud and on-premises installations).
