### ISSUE TITLE
Validate uniqueness of a documentation section

### ISSUE THREAD

**Issue by jp7677** [structurizr/java#202]
Hi,

The commit https://github.com/structurizr/java/commit/054e58f0480a5036e504daf5ccd638e643927335 dropped the section title which also served as the unique attribute for a section in `Section.equals(Object object)`. The uniqueness of a title was also validated in `checkSectionIsUnique(String title)` before adding a new section, thus an exception was raised when adding an already existing title.

The `Section.equals(Object object)` relies now on the section content, but the uniqueness of the content is not validated. Thus two sections with the same content can be added. But since the sections are stored internally in a Set which relies on `Section.equals(Object object)`, the second section is silently dropped.

I guess it is better to restore the validation of the "unique" attribute, thus the `content` now, so that adding the same section content twice fails immediately.

**Comment by simonbrowndotje** [comment]
I've just made commit 87dc677 ... this removes the content validation check entirely because it resolves a couple of recurring issues related to documentation importing failing when run against empty files, which often happens when people are creating templates for others to use. This commit also switches `sections` to be a list, which I think is more appropriate.

So with all that in mind, I'm not sure that it's worth validating section uniqueness.

**Comment by jp7677** [comment]
Yes, this solution is perfectly fine too. My main point was that sections got silently dropped (took me a while to find this in our tests after updating ;) ), which is now also no longer the case, thanks!
