### ISSUE TITLE
Can't import "com.structurizr.api.StructurizrClient"

### ISSUE THREAD

**Issue by thefooly** [structurizr/java#26]
Hello,

I am trying to use Structurizr with Maven, but unfortunately I can't import the _"com.structurizr.api.StructurizrClient"_  class (version 0.6.0) even if I am following the tutorial you provided.

I ran the _"./gradlew publishToMavenLocal"_ command and I added the dependencies to my pom file. Everything loads and works fine until I try to import the _"com.structurizr.api.StructurizrClient"_ class. In fact in my dependencies (even if I have them in my pom file), I can't see any jar called _"structuriz-client-0.6.0.jar"_. 

I checked in my local Maven repository and I couldn't find the jar there. I can't manually download the jar file from Bintray, so I tried to find another solution to my problem.

Currently I made it work by downloading version **0.3.2** of Structurizr and then by manually adding to the build path of my project _"structuriz-client-0.3.2.jar"_.  This allows me to import (and use) the _"com.structurizr.api.StructurizrClient"_ class.

It looks like that in the Bintray repository the client-0.6.0 jar file is not there, or am I doing anything wrong?

Thanks!

**Comment by thefooly** [comment]
Sorry for the double post:

I saw in a commit that you merged _structurizr-client_ into _structurizr-core_. Unfortunately the "api" package is not inside the core.jar. (even if in the git repository it is there)

**Comment by simonbrowndotje** [comment]
The structurizr-client-0.6.0.jar file certainly seems to be on Bintray -> https://bintray.com/structurizr/maven/structurizr-java/0.6.0/view#files/com/structurizr/structurizr-client/0.6.0

Since the files are hosted on Bintray (jcenter) rather than Maven Central, you'll need to add "http://jcenter.bintray.com" as an additional repository in your Maven build file -> https://maven.apache.org/guides/mini/guide-multiple-repositories.html

Apologies, this is missing from the instructions. Let me know if that fixes the problem.
