### ISSUE TITLE
SourceCodeComponentFinderStrategy fails to extract any description!

### ISSUE THREAD

**Issue by roxspring** [structurizr/java#62]
We have a potentially weird setup (although surely not that uncommon):

Our source repo contains `com.example.ThingImpl` which implements a `com.example.Thing` interface which we inherit from an dependency jar (it's generated from a swagger definition through ci). We religiously add relevant javadocs to the implementation but the generated interface has none.

Running some of the spring component finders manages to identify a component "Thing" with CodeElements for Thing (interface, primary) and ThingImpl (class, supporting). Then when trying to identify the Component description it considers the non-existent interface description but ignores ThingImpl's juicy javadocs because it's a "supporting" class.

Proposal: Modify `SourceCodeComponentFinderStrategy` so that:
1. If the Component already has a description then don't touch it.
2. Else prefer any Primary `CodeElement` description.
3. Else accept any Supporting `CodeElement` description.
4. Else give up and leave a blank description.

I'm slightly concerned about what might happen if multiple documented Primary `CodeElement`s are found with javadocs - which will be picked? Similarly with multiple documented Secondary `CodeElement`s are found. But I know this isn't the case for my code base so I'm ignoring it for now.

Any improvements to this approach?

**Comment by simonbrowndotje** [comment]
For any given component, there is a single primary code element (usually the interface) and zero or more supporting code elements. Since the javadoc is used to set descriptions on all of the code elements, so you could therefore write some code that executes after the component finders have run, to propagate the descriptions up to the component level, if a component doesn't have a description. The problem you'll need to overcome is choosing the most appropriate supporting code element to pull the description from.

**Comment by roxspring** [comment]
You're right I could probably post-process in the client code but I figure that if there's exactly one Supporting CodeElement with a description and no better option then propagate that up. Offered up a PR which does that and wimps out if there are multiple Supporting CodeElements to consider.
